# -*- mode:python -*-

Import("*")

Source("interrupts.cc")

#SimObject("IntermittentCPU.py", sim_objects=["IntermittentCPU"])

SimObject("IntermittentInterrupts.py",
        sim_objects=["IntermittentInterrupts"],
        enums=["IntermittentOutageSignature"]
)
